// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX75bIu3QQGiwyJRTZQthc5OEHNDHNTf0',
    appId: '1:379834680294:web:1e27db553cb6f048b08c27',
    messagingSenderId: '379834680294',
    projectId: 'steps-96f64',
    authDomain: 'steps-96f64.firebaseapp.com',
    storageBucket: 'steps-96f64.firebasestorage.app',
    measurementId: 'G-CDZGEFZZ1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvGLosP34V0Rwe1sylG-n_cRrR9dh9tJE',
    appId: '1:379834680294:android:01ab58b951078805b08c27',
    messagingSenderId: '379834680294',
    projectId: 'steps-96f64',
    storageBucket: 'steps-96f64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuN7tjMb2dA5PRZeFgICPUpYB31qNOTMk',
    appId: '1:379834680294:ios:7b68ce700fb6b3eab08c27',
    messagingSenderId: '379834680294',
    projectId: 'steps-96f64',
    storageBucket: 'steps-96f64.firebasestorage.app',
    iosBundleId: 'ai.anantata.anantata',
  );
}
